name: Comment on Pull Request

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  comment-job:
    runs-on: ubuntu-latest

    steps:
    - name: Comment on Pull Request
      env:
        GITHUB_TOKEN: ${{secrets.GH_PAT}}
      run: |
        PR_NUMBER=${{github.event.pull_request.number}}
        curl -X POST -H "authorization: token $GITHUB_TOKEN"\
        -d '{"body": "Thanks for the pr"}'\
        https://api.github.com/leela-maanasa/training_session/issues/$PR_NUMBER/comments
